// Code generated by protoc-gen-go.
// source: proto/report.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/report.proto
	proto/response.proto

It has these top-level messages:
	ReportRequest
	ReportResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReportRequest struct {
	Time  int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Reply string `protobuf:"bytes,3,opt,name=reply" json:"reply,omitempty"`
	Seq   int32  `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	Sig   []byte `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto1.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
