// Code generated by protoc-gen-go.
// source: proto/response.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReportResponse struct {
	Diff  int64  `protobuf:"varint,1,opt,name=diff" json:"diff,omitempty"`
	Time  int64  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Trans int32  `protobuf:"varint,4,opt,name=trans" json:"trans,omitempty"`
	Seq   int32  `protobuf:"varint,5,opt,name=seq" json:"seq,omitempty"`
	Sig   []byte `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto1.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
