// Code generated by protoc-gen-go.
// source: tx.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	tx.proto

It has these top-level messages:
	TxMsg
	InitialReport
	Report
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type TxMsg struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Sig []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Seq int32  `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	// Types that are valid to be assigned to Inner:
	//	*TxMsg_InitialReport
	//	*TxMsg_Report
	Inner isTxMsg_Inner `protobuf_oneof:"inner"`
}

func (m *TxMsg) Reset()                    { *m = TxMsg{} }
func (m *TxMsg) String() string            { return proto1.CompactTextString(m) }
func (*TxMsg) ProtoMessage()               {}
func (*TxMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isTxMsg_Inner interface {
	isTxMsg_Inner()
}

type TxMsg_InitialReport struct {
	InitialReport *InitialReport `protobuf:"bytes,4,opt,name=initialReport,oneof"`
}
type TxMsg_Report struct {
	Report *Report `protobuf:"bytes,5,opt,name=report,oneof"`
}

func (*TxMsg_InitialReport) isTxMsg_Inner() {}
func (*TxMsg_Report) isTxMsg_Inner()        {}

func (m *TxMsg) GetInner() isTxMsg_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *TxMsg) GetInitialReport() *InitialReport {
	if x, ok := m.GetInner().(*TxMsg_InitialReport); ok {
		return x.InitialReport
	}
	return nil
}

func (m *TxMsg) GetReport() *Report {
	if x, ok := m.GetInner().(*TxMsg_Report); ok {
		return x.Report
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TxMsg) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _TxMsg_OneofMarshaler, _TxMsg_OneofUnmarshaler, _TxMsg_OneofSizer, []interface{}{
		(*TxMsg_InitialReport)(nil),
		(*TxMsg_Report)(nil),
	}
}

func _TxMsg_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*TxMsg)
	// inner
	switch x := m.Inner.(type) {
	case *TxMsg_InitialReport:
		b.EncodeVarint(4<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.InitialReport); err != nil {
			return err
		}
	case *TxMsg_Report:
		b.EncodeVarint(5<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Report); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TxMsg.Inner has unexpected type %T", x)
	}
	return nil
}

func _TxMsg_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*TxMsg)
	switch tag {
	case 4: // inner.initialReport
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(InitialReport)
		err := b.DecodeMessage(msg)
		m.Inner = &TxMsg_InitialReport{msg}
		return true, err
	case 5: // inner.report
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(Report)
		err := b.DecodeMessage(msg)
		m.Inner = &TxMsg_Report{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TxMsg_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*TxMsg)
	// inner
	switch x := m.Inner.(type) {
	case *TxMsg_InitialReport:
		s := proto1.Size(x.InitialReport)
		n += proto1.SizeVarint(4<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *TxMsg_Report:
		s := proto1.Size(x.Report)
		n += proto1.SizeVarint(5<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InitialReport struct {
	Time int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *InitialReport) Reset()                    { *m = InitialReport{} }
func (m *InitialReport) String() string            { return proto1.CompactTextString(m) }
func (*InitialReport) ProtoMessage()               {}
func (*InitialReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Report struct {
	Diff int64 `protobuf:"varint,1,opt,name=diff" json:"diff,omitempty"`
	Time int64 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto1.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*TxMsg)(nil), "proto.TxMsg")
	proto1.RegisterType((*InitialReport)(nil), "proto.InitialReport")
	proto1.RegisterType((*Report)(nil), "proto.Report")
}

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0xa9, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xab, 0x19, 0xb9, 0x58, 0x43, 0x2a, 0x7c,
	0x8b, 0xd3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x80,
	0x2c, 0x21, 0x01, 0x2e, 0xe6, 0xe2, 0xcc, 0x74, 0x09, 0x26, 0xa0, 0x00, 0x4f, 0x10, 0x88, 0x09,
	0x16, 0x49, 0x2d, 0x94, 0x60, 0x06, 0x8a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x36, 0x5c, 0xbc, 0x99,
	0x79, 0x99, 0x25, 0x99, 0x89, 0x39, 0x41, 0xa9, 0x05, 0xf9, 0x45, 0x25, 0x12, 0x2c, 0x40, 0x39,
	0x6e, 0x23, 0x11, 0x88, 0x1d, 0x7a, 0x9e, 0xc8, 0x72, 0x1e, 0x0c, 0x41, 0xa8, 0x8a, 0x85, 0xd4,
	0xb9, 0xd8, 0x8a, 0x20, 0xda, 0x58, 0xc1, 0xda, 0x78, 0xa1, 0xda, 0xe0, 0xea, 0xa1, 0xd2, 0x4e,
	0xec, 0x5c, 0xac, 0x99, 0x79, 0x79, 0xa9, 0x45, 0x4a, 0xe6, 0x5c, 0xbc, 0x28, 0x66, 0x0a, 0x09,
	0x71, 0xb1, 0x94, 0x64, 0xe6, 0xa6, 0x82, 0x9d, 0xcd, 0x1c, 0x04, 0x66, 0x83, 0xc4, 0xf2, 0x12,
	0x81, 0x62, 0x4c, 0x60, 0xaf, 0x80, 0xd9, 0x4a, 0x06, 0x5c, 0x6c, 0x08, 0x1d, 0x29, 0x99, 0x69,
	0x69, 0x30, 0x1d, 0x20, 0x36, 0xdc, 0x14, 0x26, 0x84, 0x29, 0x49, 0x6c, 0x60, 0xb7, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xc0, 0x3b, 0x83, 0x32, 0x01, 0x00, 0x00,
}
